version: '3.8'

services:
  web:
    build: .
    container_name: mathworksheet-app
    ports:
      - "8090:8090"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://mathuser:mathpassword@host.docker.internal:5432/mathworksheetdb
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mathworksheet-network

networks:
  mathworksheet-network:
    driver: bridge
